const FEB = "Feb";

export const library = [
  {
    id: "r1",
    name: "Onions",
    type: "Root plant",
    season: [FEB, "Apr", "May", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb"],
    space: "",
  },

  {
    id: "r2",
    name: "Shallots",
    type: "Root plant",
    season: [
      "Mar",
      "Apr",
      "May",
      "June",
      "July",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
      "Jan",
      "Feb",
    ],

    space: "",
  },

  {
    id: "r3",
    name: "Garlic",
    type: "Root plant",
    season: ["Mar", "Apr", "May", "June", "July", "Aug", "Sep", "Oct", "Nov"],
    space: "",
  },

  {
    id: "r4",
    name: "Beetroot",
    type: "Root plant",
    season: [
      "Mar",
      "Apr",
      "May",
      "June",
      "July",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
      "Jan",
      "Feb",
    ],
    space: "",
  },

  {
    id: "r5",
    name: "Radishes",
    type: "Root plant",
    season: ["Mar", "Apr", "May", "Sep", "Oct", "Nov"],
    space: "",
  },

  {
    id: "r6",
    name: "Turnips",
    type: "Root plant",
    season: ["Mar", "Apr", "May", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb"],
    space: "",
  },

  {
    id: "r7",
    name: "Carrots",
    type: "Root plant",
    season: [
      "Mar-",
      "Apr-",
      "May-",
      "June-",
      "July-",
      "Aug-",
      "Sep-",
      "Oct-",
      "Nov-",
      "Dec-",
      "Jan-",
      "Feb",
    ],
    space: "",
  },

  {
    id: "r8",
    name: "Potatoes",
    type: "Root plant",
    season: [
      "Mar-",
      "Apr-",
      "May-",
      "June-",
      "July-",
      "Aug-",
      "Sep-",
      "Oct-",
      "Nov-",
      "Dec-",
      "Jan-",
      "Feb",
    ],
    space: "",
  },

  {
    id: "ly1",
    name: "Broccoli",
    type: "Leafy plants",
    season: ["Mar-", "Apr-", "May-", "Sep-", "Oct-", "Nov"],
    space: "",
  },

  {
    id: "ly2",
    name: "Lettuce",
    type: "Leafy plants",
    season: ["Mar-", "Apr-", "May-", "Sep-", "Oct-", "Nov"],
    space: "",
  },

  {
    id: "ly3",
    name: "Cabbage",
    type: "Leafy plants",
    season: [
      "Mar-",
      "Apr-",
      "May-",
      "Sep-",
      "Oct-",
      "Nov-",
      "Dec-",
      "Jan-",
      "Feb",
    ],
    space: "",
  },

  {
    id: "ly4",
    name: "Cauliflower",
    type: "Leafy plants",
    season: ["Sep-", "Oct-", "Nov"],
    space: "",
  },

  {
    id: "ly5",
    name: "Spinach",
    type: "Leafy plants",
    season: ["Mar-", "Apr-", "May-", "Sep-", "Oct-", "Nov"],
    space: "",
  },

  {
    id: "le1",
    name: "Runner beans",
    type: "Legumes",
    season: [
      "Mar-",
      "Apr-",
      "May-",
      "June-",
      "July-",
      "Aug-",
      "Sep-",
      "Oct-",
      "Nov-",
      "Dec-",
      "Jan-",
      "Feb",
    ],
    space: "",
  },

  {
    id: "le2",
    name: "Lentil",
    type: "Legumes",
    season: [
      "Mar-",
      "Apr-",
      "May-",
      "June-",
      "July-",
      "Aug-",
      "Sep-",
      "Oct-",
      "Nov-",
      "Dec-",
      "Jan-",
      "Feb",
    ],
    space: "",
  },

  {
    id: "le3",
    name: "Peas",
    type: "Legumes",
    season: ["Mar-", "Apr-", "May-", "Sep-", "Oct-", "Nov"],
    space: "",
  },

  {
    id: "le4",
    name: "Garbanzos",
    type: "Legumes",
    season: [
      "Mar-",
      "Apr-",
      "May-",
      "June-",
      "July-",
      "Aug-",
      "Sep-",
      "Oct-",
      "Nov-",
      "Dec-",
      "Jan-",
      "Feb",
    ],
    space: "",
  },

  {
    id: "fr1",
    name: "Cucumbers",
    type: "Fruiting plants",
    season: ["June-", "July-", "Aug"],
    space: "",
  },

  {
    id: "fr2",
    name: "Courgettes",
    type: "Fruiting plants",
    season: [
      "Mar-",
      "Apr-",
      "May-",
      "June-",
      "July-",
      "Aug-",
      "Sep-",
      "Oct-",
      "Nov-",
      "Dec-",
      "Jan-",
      "Feb",
    ],
    space: "",
  },

  {
    id: "fr3",
    name: "Tomatoes",
    type: "Fruiting plants",
    season: [
      "Mar-",
      "Apr-",
      "May-",
      "June-",
      "July-",
      "Aug-",
      "Sep-",
      "Oct-",
      "Nov-",
      "Dec-",
      "Jan-",
      "Feb",
    ],
    space: "",
  },

  {
    id: "fr4",
    name: "Pumpkins",
    type: "Fruiting plants",
    season: ["Sep-", "Oct-", "Nov-", "Dec-", "Jan-", "Feb"],
    space: "",
  },

  {
    id: "fr5",
    name: "Aubergines",
    type: "Fruiting plants",
    season: ["June-", "July-", "Aug"],
    space: "",
  },

  {
    id: "fr6",
    name: "Sweetcorn",
    type: "Fruiting plants",
    season: [
      "Mar-",
      "Apr-",
      "May-",
      "June-",
      "July-",
      "Aug-",
      "Sep-",
      "Oct-",
      "Nov-",
      "Dec-",
      "Jan-",
      "Feb",
    ],
    space: "",
  },
  // // {
  // // "id": "fr6",
  // // "name": "Sweetcorn",
  // // "type": "Fruiting plants",
  // // "season":{
  // //     "Mar",
  // //     "Apr",
  // //     "May",
  // //     "June",
  // //     "July",
  // //     "Aug",
  // //     "Sep",
  // //     "Oct",
  // //     "Nov",
  // //     "Dec",
  // //     "Jan",
  // //     "Feb"
  // // }
  // // "space
  // // }
];
